title: Tech Notes
description: >-
  This is where I brain dump anything I learn about programming, devops and general tech.
author: Nathan Dench
url: "https://ndench.github.io"
google_analytics: UA-113477794-1
timezone: Australia/Brisbane
show_excerpts: true
permalink: /:categories/:title

# Social
twitter_username: nathandench
github_username: ndench
linkedin_username: nathandench
rss: rss

# Disqus comments
disqus:
  shortname: ndench

# Don't show any other pages in the nav
header_pages: 
  - about.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

defaults:
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post
      comments: false

# Build drafts
collections:
  drafts:
    output: true
    permalink: /drafts/:path/
